spring:
  application:
    name: notes
  datasource:
    url: jdbc:mysql://backend.cb4628uq0oj9.ap-south-1.rds.amazonaws.com:3306/backend
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8080
  servlet:
    context-path: /api

# Specify the configuration of OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true