spring:
  application:
    name: notes
  datasource:
    url: jdbc:mysql://localhost:3306/backend
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    context-path: /api

# Specify the configuration of OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true